### ISSUE TITLE
Some titles exceed 100 characters and are too long for YouTube

### ISSUE THREAD

**Issue by hypha** [egeakman/review-sheet-generator#2]
Some titles might exceed YouTube title max length. Can consider manually investigate before exploring how to automate.

**Comment by egeakman** [comment]
Thanks for the issue!

These are mostly the sessions with multiple speakers (e.g. panels, etc.). Is there anything on your mind about how to approach this?

**Comment by hypha** [comment]
I did two things manually in the past : 
1. For panels, I removed the speakers' names from the YouTube title. The abstracts for panels in 2023 already included the list of speakers, which was sufficient. For 2024, the sustainability panel does not list speakers (in fact, it barely has anything); while the CPython panel does. Therefore, I'm uncertain whether we should always include the panel speakers in the YouTube descriptions as part of the script or ensure that the list of panel speakers is always included in Pretalx.
2. For any other title that exceeds 100 characters, I might remove the speakers' names from the title and place them in the description, or shorten the title. For example, in 2024, the only non-panel long title is: `How we used vectorization for 1000x Python speedups (no C or Spark needed!) — Jonathan Hollenbeck, Justine Wezenaar`. In this case, I might consider keeping the speakers' names but removing (no C or Spark needed!). However, I personally think it would be easier and better to uniformly place the speakers' names in the description within the script.

WDYT?

**Comment by egeakman** [comment]
I think we can do something like this (pseudocode):

```
if youtube_title too long:
  youtube_title = youtube_title.remove(speaker_names)
  
youtube_description = f"""\
...
{session.title} by {session.speakers}
{session.website_url}
...
```
